//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanGu {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyzerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AnalyzerResource() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanGu.AnalyzerResource", typeof(AnalyzerResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与  beat	beat	beaten
        ///become	became	become
        ///begin	began	begun
        ///bend	bent	bent
        ///bet	bet	bet
        ///bid	bid	bid
        ///bite	bit	bitten
        ///bleed	bled	bled
        ///blow	blew	blown
        ///break	broke	broken
        ///breed	bred	bred
        ///bring	brought	brought
        ///broadcast	broadcast	broadcast
        ///build	built	built
        ///buy	bought	bought
        ///catch	caught	caught
        ///choose	chose	chosen
        ///cling	clung	clung
        ///come	came	come
        ///cost	cost	cost
        ///creep	crept	crept
        ///cut	cut	cut
        ///deal	dealt	dealt
        ///dig	dug	dug
        ///do	did	done
        ///draw	drew	drawn
        ///dream	dreamed	dreamt
        ///drink	drank	drunk
        ///driv [字符串的其余部分被截断]”； 类似的本地化字符串。
        /// </summary>
        public static string INFINITIVE {
            get {
                return ResourceManager.GetString("INFINITIVE", resourceCulture);
            }
        }
    }
}
